title: Minimal theme
logo: /assets/img/hans-jurgen-mager-qQWV91TTBrE-unsplash.jpg
description:
  <p align="center">
  <a href="https://github.com/Roger-Arnold/fraud_detection.git">GitHub</a>
  
  <br>   
  I'm an emerging data enthusiast
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
